#!/bin/bash
set -e
set -x

# setup servers/users/cluster
./server.sh

# setup checks
./check_cluster.sh

# generate load
./genload.sh

# sleep a bit to allow load to raise
sleep 60

# kill node2
docker kill node2

# sleep a bit to allow rabbitmq to cleanup things.
sleep 10

# stop load
docker ps | grep rpc_flood | awk '{ print $1 }' | xargs -n1 docker rm --force 

# check cluster for broken queues, bindings, ...
./check_cluster.sh


# cleanup
# docker ps -aq | xargs docker rm --force 
